### ISSUE TITLE
CURRENTPAGENAME to variable

### ISSUE THREAD

**Issue by jbnv** [dvargas92495/roamjs-com#739]
There's an inconsistency in the `CURRENT*` commands: CURRENTBLOCKREF and CURRENTBLOCKCONTENT store in a variable, but 
CURRENTPAGENAME does not. I've run into issues calling CURRENTPAGENAME within JS code; it's problematic when a page name contains quotes. Being able to save CURRENTPAGENAME to a variable like with the CURRENTBLOCK* commands should eliminate that problem.

**Comment by dvargas92495** [comment]
I like the idea of making all three consistent:
- return to block if no variable
- set if variable

In the meantime, you should be able to do `<%SET:var,<%CURRENTPAGENAME%>%>`
