### ISSUE TITLE
Update for synonyms/aliases

### ISSUE THREAD

**Issue by Meh-S-Eze** [dvargas92495/roamjs-com#750]
From Abhay related to AutoAlias Do not alias within URLs / Markdown links

My Request
Would it be possible to use another character instead of  " , " to separate aliases?  This is a common way of separating last name first name within employee directories. I would suggest +  OR make it configurable.

**Comment by dvargas92495** [comment]
> From Abhay related to AutoAlias Do not alias within URLs / Markdown links

This is already expected behavior - is there a counterexample?

No way to specify a seperate another delimiter yet

**Comment by dvargas92495** [comment]
All future issues related to aliases should go to https://github.com/dvargas92495/autotag
